baseURL: https://en.letswrite.tw/
publishDir: docs
timeZone: Asia/Taipei

# sitemap
sitemap:
  changefreq: weekly # always, hourly, daily, weekly, monthly, yearly, never
  filename: sitemap.xml
  priority: 1.0

title: Let's Write, EN

# 導覽列
menu:
  main:
  - name: Index
    title: Index
    url: /
    weight: 1
  - name: Front-End
    title: Front-End
    url: /categories/front-end/
    weight: 2
  - name: Google
    title: Google
    url: /categories/google/
    weight: 3

# copyright
copyright: Let's Write. All Rights Reserved.

# 引言的長度
summaryLength: 15

# 客製參數
params:
  subtitle: Front-end engineer August's study notes — solving problems, in simple ways.
  mainColor: '#42A6F7'
  favicon: https://letswritetw.github.io/letswritetw/dist/img/logo_512.png

